//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MercadoEnvio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La FUNCIONALIDAD que se quiere agregar, ya existe.
        /// </summary>
        internal static string ErrorAgregarFuncionalidad {
            get {
                return ResourceManager.GetString("ErrorAgregarFuncionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo conectar a la BD.
        /// </summary>
        internal static string ErrorBD {
            get {
                return ResourceManager.GetString("ErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo DESCRIPCIÓN no puede estar vacío.
        /// </summary>
        internal static string ErrorDescripcionVacia {
            get {
                return ResourceManager.GetString("ErrorDescripcionVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo ESTADO no puede estar vacío.
        /// </summary>
        internal static string ErrorEstadoVacio {
            get {
                return ResourceManager.GetString("ErrorEstadoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Guardar.
        /// </summary>
        internal static string ErrorGuardado {
            get {
                return ResourceManager.GetString("ErrorGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o contraseña invalidos.
        /// </summary>
        internal static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ROL debe tener almenos una FUNCIONALIDAD.
        /// </summary>
        internal static string ErrorRolSinFuncionalidad {
            get {
                return ResourceManager.GetString("ErrorRolSinFuncionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al ejecutar SP.
        /// </summary>
        internal static string ErrorSP {
            get {
                return ResourceManager.GetString("ErrorSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el manejo de data-table.
        /// </summary>
        internal static string ErrorTable {
            get {
                return ResourceManager.GetString("ErrorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la transacción.
        /// </summary>
        internal static string ErrorTrans {
            get {
                return ResourceManager.GetString("ErrorTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentos restantes: .
        /// </summary>
        internal static string IntentosRestantes {
            get {
                return ResourceManager.GetString("IntentosRestantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario bloqueado. Contacte al administrador.
        /// </summary>
        internal static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
    }
}
