//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MercadoEnvio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacte al administrador..
        /// </summary>
        internal static string ContactarAdministrador {
            get {
                return ResourceManager.GetString("ContactarAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        internal static string ContraseñaIncorrecta {
            get {
                return ResourceManager.GetString("ContraseñaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La funcionalidad seleccionada ya fue agregada..
        /// </summary>
        internal static string ErrorAgregarFuncionalidad {
            get {
                return ResourceManager.GetString("ErrorAgregarFuncionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar establecer conexión con la base de datos..
        /// </summary>
        internal static string ErrorBD {
            get {
                return ResourceManager.GetString("ErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar iniciar la transacción..
        /// </summary>
        internal static string ErrorBeginTrans {
            get {
                return ResourceManager.GetString("ErrorBeginTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Descripción corta&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionCortaVacia {
            get {
                return ResourceManager.GetString("ErrorDescripcionCortaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Descripción larga&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionLargaVacia {
            get {
                return ResourceManager.GetString("ErrorDescripcionLargaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Descripción&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionVacia {
            get {
                return ResourceManager.GetString("ErrorDescripcionVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar finalizar la transacción..
        /// </summary>
        internal static string ErrorEndTrans {
            get {
                return ResourceManager.GetString("ErrorEndTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Estado&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorEstadoVacio {
            get {
                return ResourceManager.GetString("ErrorEstadoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar.
        /// </summary>
        internal static string ErrorGuardado {
            get {
                return ResourceManager.GetString("ErrorGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha instanciado ninguna conexión..
        /// </summary>
        internal static string ErrorNoConnection {
            get {
                return ResourceManager.GetString("ErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha instanciado ninguna transacción..
        /// </summary>
        internal static string ErrorNoTrans {
            get {
                return ResourceManager.GetString("ErrorNoTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar deshacer la transacción..
        /// </summary>
        internal static string ErrorRollbackTrans {
            get {
                return ResourceManager.GetString("ErrorRollbackTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol debe tener al menos una funcionalidad..
        /// </summary>
        internal static string ErrorRolSinFuncionalidad {
            get {
                return ResourceManager.GetString("ErrorRolSinFuncionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar ejecutar el stored procedure.
        /// </summary>
        internal static string ErrorSP {
            get {
                return ResourceManager.GetString("ErrorSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar ejecutar la transacción..
        /// </summary>
        internal static string ErrorTrans {
            get {
                return ResourceManager.GetString("ErrorTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fastforward {
            get {
                object obj = ResourceManager.GetObject("fastforward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fastreverse {
            get {
                object obj = ResourceManager.GetObject("fastreverse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentos restantes: .
        /// </summary>
        internal static string IntentosRestantes {
            get {
                return ResourceManager.GetString("IntentosRestantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rubro ha sido creado exitosamente.
        /// </summary>
        internal static string RubroCreado {
            get {
                return ResourceManager.GetString("RubroCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario bloqueado. .
        /// </summary>
        internal static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido creado exitosamente.
        /// </summary>
        internal static string UsuarioCreado {
            get {
                return ResourceManager.GetString("UsuarioCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario deshabilitado. .
        /// </summary>
        internal static string UsuarioDeshabilitado {
            get {
                return ResourceManager.GetString("UsuarioDeshabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ingresado no existe.
        /// </summary>
        internal static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
    }
}
