USE GD1C2016
GO
DROP TABLE MASTERDBA.Calificaciones
GO
DROP TABLE MASTERDBA.Roles_Funcionalidades
GO
DROP TABLE MASTERDBA.Usuarios_Roles
GO
DROP TABLE MASTERDBA.Funcionalidades
GO
DROP TABLE MASTERDBA.Roles
GO
DROP TABLE MASTERDBA.Facturas_Items
GO
DROP TABLE MASTERDBA.Facturas
GO
DROP TABLE MASTERDBA.Formas_Pago
GO
DROP TABLE MASTERDBA.Ofertas
GO
DROP TABLE MASTERDBA.Compras
GO
DROP TABLE MASTERDBA.Publicaciones_Visibilidad
GO
DROP TABLE MASTERDBA.Publicaciones
GO
DROP TABLE MASTERDBA.Rubros
GO
DROP TABLE MASTERDBA.Clientes
GO
DROP TABLE MASTERDBA.Empresas
GO
DROP TABLE MASTERDBA.Usuarios
GO
DROP TABLE MASTERDBA.Visibilidad_Publicacion
GO
DROP TABLE MASTERDBA.Estado_Publicacion
GO
DROP TABLE MASTERDBA.Tipo_Publicacion
GO

DROP SCHEMA MASTERDBA
GO